name: Common CI Workflow

on:
  workflow_call:
    inputs:
      run_build:
        description: "Indicates if build step should be run"
        required: false
        default: false
        type: boolean
    secrets:
      github_token:
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install --force

      - name: Run Lint
        run: npm run lint --force

      - name: Run Tests
        run: npm run test --force

      - name: Build Application
        if: ${{ inputs.run_build }}
        run: npm run build --force
