name: Deployment CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install Dependencies
        run: npm install --force

      - name: Run Lint
        run: npm run lint --force

      - name: Run Tests
        run: npm run test --force

      - name: Build Application and automatically deploy to GitHub Pages
        run: npm run build --force
