name: Deployment CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/ci.yml
    with:
      run_build: true
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist