name: Development CI

on:
  push:
    branches:
      - development

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      run_build: false
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
